# Generated by Django 3.1.5 on 2021-11-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='game.participant')),
                ('ethnicity', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('game_exp', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='finished_game',
            field=models.BooleanField(default=False),
        ),
    ]
