# Generated by Django 3.1.5 on 2021-11-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20211104_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='load_date',
            new_name='accept_dt',
        ),
        migrations.AlterField(
            model_name='participant',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='game_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='worker_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
