# Generated by Django 3.1.5 on 2021-11-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20211104_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='edu',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
