# Generated by Django 3.1.5 on 2021-12-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20211129_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='hit_id',
        ),
        migrations.AddField(
            model_name='participant',
            name='completion_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='submitted_demographics',
            field=models.BooleanField(default=False),
        ),
    ]
