# Generated by Django 3.1.5 on 2021-12-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20211201_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='submitted_demographics',
        ),
    ]
